### ISSUE TITLE
CLAIMING Rule

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup#381]
ALWAYS make sure that whenever you change the status to something OTHER THAN "Open, unassigned," that the user claims the work order.  

This is a big deal.

**Comment by aarontitus** [comment]
Currently this rule is implemented through AJAX on the map, but is not implemented on the form. Fixing this bug will require at least a temporary re-think of the form generation process and perhaps (finally) integrating our incident schema into the database, instead of markup.
Here is the Heroku Form Generator: https://docs.google.com/spreadsheets/d/1tFpyHhNFPSlgAIq3mp8vNUM-nULd-oqjBVfZwlLihiE/edit#gid=1842230246
