### ISSUE TITLE
User Deactivate

### ISSUE THREAD

**Issue by arroyoDev** [CrisisCleanup/crisiscleanup#387]
The system currently has no way to de-activate a user.  We need to have that setting that prevents access and hides them form lists everywhere.

**Comment by astashov** [comment]
I'll try to take this

**Comment by astashov** [comment]
Approach: we could add `is_disabled` boolean field to `users` db, `false` by default. Then, we add a `default_scope`, which is `is_active: false` to `User` model. It's usually an antipattern, but in this case since we'll have to use it like in 90% of cases, should be okay.

Then, we'll exclude that default scope in `/admin/users`, and add a field - checkbox `is_disabled` to the edit user form.

What do you think?

**Comment by tsanders** [comment]
Yes, that should definitely work.
